require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "lib/api/**/*"

#
# Lint
#

Lint/EmptyWhen:
  Enabled: false

Lint/RescueException:
  Enabled: false

#
# Metrics
#

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

#
# Style
#

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Enabled: false

#
# Layout
#

Layout/LineLength:
  Max: 130

#
# Rspec
#
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

#
# Naming
#
Naming/AccessorMethodName:
  Enabled: false
