# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth/service.proto for package 'Stately.Auth'

require 'grpc'
require 'api/auth/service_pb'

module Stately
  module Auth
    module AuthService
      # AuthService is the service for vending access tokens used to connect to
      # StatelyDB. This API is meant to be used from SDKs. Access Keys are created
      # and managed from the stately.dbmanagement.UserService.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'stately.auth.AuthService'

        # GetAuthToken returns a short-lived access token from some proof of
        # identity. This operation will fail if the identity cannot be verified.
        rpc :GetAuthToken, ::Stately::Auth::GetAuthTokenRequest, ::Stately::Auth::GetAuthTokenResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
